### ISSUE TITLE
extreme pitch values at start and end?

### ISSUE THREAD

**Issue by dreamk73** [bjbschmitt/AMFM_decompy#2]
Thank you for providing this code. I am finding it very useful for getting a smooth pitch contour for a long list of sentences. But I have one issue and I am not sure if it is possible to fix it with the current implementation of the algorithm. Often times, especially at the end of the sentence, the interpolated values (samp_interp) go extremely high, making the last few pitch points in the spoken sentence very unreliable. Is there a parameter I can set to change this, so I get better pitch values at the end of the sentence and sometimes at the beginning as well?

**Comment by bjbschmitt** [comment]
Hi, thanks for your report!
Could you send me any sample sound file where your problem occurs? I want to re-create your issue here to check what's the best solution for it.

**Comment by dreamk73** [comment]
Sure, thank you for taking a look. I am just testing with a very simple
file right now, but am getting the same kind of errors with other files. I
also included the example script and my output file.

Esther

**Comment by bjbschmitt** [comment]
Ok, I'll be waiting for your file and script. If the sound file is too big to pass here in github, please send it to email.

**Comment by dreamk73** [comment]
Ok, I hope this works. I had to pack it into a zip file.

[ex.zip](https://github.com/bjbschmitt/AMFM_decompy/files/716499/ex.zip)

**Comment by bjbschmitt** [comment]
Hi, your code worked fine here. As I thought, there was indeed a problem in using the interpolation algorithm in order to extrapolate the values that come before the first voiced frame and also those after the last voiced frame.

Anyway, here's the fixed version. I've already modified your original script (ex1.py) in order to run it using this new code (that I temporarily called new_pYAAPT.py). It worked fine here, so please check if it solves the issue with you problematic wav files.

Once you confirm that everything is fine, then I'll update the AMFM_decompy repositories in github and in pypi.

[ex1.zip](https://github.com/bjbschmitt/AMFM_decompy/files/718017/ex1.zip)

**Comment by dreamk73** [comment]
Thanks for fixing the bug! It looks much better now.

I have another question, when you use a frame_length of 25ms and a frame_space of 10ms, where does that put the first time stamp of the first pitch value? Since you need a full frame, I would expect it to be at 12.5ms, but I just wanted to double check.

**Comment by bjbschmitt** [comment]
Your guess is correct, but not 100%, because when the algorithm convert the frame_length and frame_space sizes from milliseconds to sample values, it may be necessary round them to integer values. So, it depends on your sample frequency and on the frame_length and frame_space sizes.

For example:
Your "move.wav" file has a sample frequency of 22050 Hz. Thus:

frame_length (in samples) = frame_length*fs -> 0.025*22050 -> 551.25 -> 551 samples
frame_space (in samples) = frame_space*fs -> 0.01*22050 -> 220.5 -> 220 samples

But when we "recovert" these values to seconds again, we got

"real" frame_length (in s) = frame_length/fs -> 551/22050 -> 0.02498866 s
"real" frame_space (in s) = frame_space/fs -> 220/22050 -> 0.00997732 s

Therefore, your frame_length is actually 24.998 ms and your frame_space is 9.9773 ms.

So, answering you question, since that the frame_length is 551 samples and the first frame starts at sample 0 and ends at sample 550, the first time stamp is located in the middle (as you correctly guessed), at sample 275. In milliseconds, this is equivalent to

first time stamp = 275/fs -> 275/22050 -> 0.0124716 s -> 12.4716 ms

Anyway, in order make things much more easier, you don't have to calculate these values because pitch.frames_pos returns an array containing the position of each time stamp (in sample domain). You just have to convert it to time domain:

time_stamps =  pitch.frames_pos/signal.fs

I guess I'll have to enhance the documentation, I was re-reading it and this part was in fact not totally clear.

**Comment by bjbschmitt** [comment]
By the way, I was testing the new_pYAAPT.py with some files and found out that my correction wasn't working in some cases, so here's a better fix (in case you need it).
[ex1.zip](https://github.com/bjbschmitt/AMFM_decompy/files/720155/ex1.zip)

**Comment by dreamk73** [comment]
Thanks, I really appreciate it and the explanation of the time values as well. 

Esther

**Comment by bjbschmitt** [comment]
Ok, the modifications from new_pYAAPT.py have been officially committed to pYAAPT.py and the package has been updated to version 1.0.6 in both github and pypi. You can upgrade it now in your PC via pip:

pip install --upgrade AMFM_decompy

Since that the problem seems to have been solved, I'll close this topic. 
Thanks again for helping to enhance the package!
