### ISSUE TITLE
using AMFM as vocoder for speech synthesis

### ISSUE THREAD

**Issue by tuanad121** [bjbschmitt/AMFM_decompy#5]
I'm thinking of using AMFM_decompy as vocoder for parametric speech synthesis. 
It requires a high-quality analysis/synthesis (which I believe AMFM_decompy can do it) and small number of parameters. I realize that H (3 dimension matrix) keeps necessary parameters for analysis/synthesis process. With 25 harmonics, there are 25 x 3 parameters at each sampling time (not frame time). Is it right? Can we have several frames and each frame has 25 x 3 parameters??
Thanks for spending your time on my issue.^^

**Comment by bjbschmitt** [comment]
Hi tuanad121, sorry for the delay, I was away from my hometown for some days.

Yes, you are right, for each sampling time, each harmonic will have 3 parameters (amplitude, phase and instantaneous frequency). Like you've said, 25 x 3 in total.

And once that you resynthesizes the signal, you can measure its quality using the SRER parameter and compare the results with other methods. Just notice that this is just a numeric evaluation. Eventually a perceptual test with real users would give different results, since that 'speech quality' is a subjective judgement that varies from person to person.

Actually, testing the QHM method in a vocoder was one of my "suggestions for future works" from my unpublished Master thesis. So it would be interesting to see your results. I just can't guarantee that they will be better than the ones from other vocoder algorithms, but nevertheless, this is how science works X).

I would advice you take a look at the recent papers from the QHM algorithm main authors (Y. Pantazis and Y. Stylianou). Since that I left the in academia for a while, I have lost access to the IEEE database, so I haven't read their most recent papers about the subject (2015 onwards). Eventually you could find something in them that would you help in your project.

**Comment by tuanad121** [comment]
Thanks for your kind reply. ^^ I appreciate it

**Comment by bjbschmitt** [comment]
Ok, thanks. I'll close this thread since that the question seems to have been answered.
